const score = 400
console.log(score )     //output -- 400
const balance = new Number(100) //guaranteed that balance is a number
console.log(balance)    //output -- [Number : 100]

console.log(balance.toString().length); //convert balance to string and then apply length
console.log(balance.toFixed(2));        //output -- 100.00

const otherNumber = 23.8966
console.log(otherNumber.toPrecision(3));  //23.9 -- if 123.8966 then o/p is 124
/*
..syntax -- number.toPrecision(precision);
..It returns a string representation of number including specified number of digits
..if precision of the number is not specified it will throw "Syntax Error"
*/

const hundreds = 1000000
console.log(hundreds.toLocaleString());         //it displays the number with , US standard commas
console.log(hundreds.toLocaleString('en-IN'));  //now the commas are according to the indian standard

//with the number datatypes comes a lot of properties where you get :
/*
EPSILON
isFinite
isInteger
isNaN
MAX_VALUE, MAX_SAFE_INTEGER
MIN_VALUE, MIN_SAFE_INTEGER and may more
*/

//+++++++++++++++++++++++++++++++MATHS+++++++++++++++++++++++++++++++++++++++++++
console.log(Math);              //Object [Math] {} -- output
console.log(Math.abs(-4));      //this will return 4
console.log(Math.round(4.3));   //4 -- similar to normal roundoff
console.log(Math.ceil(4.2));    //5
console.log(Math.floor(4.9));    //4
/*
Math has many more functions:
..Math.min() -- function returns the smallest number from the list of arguments
..Basic syntax -- Math.min(value1, value2, ..., valueN)
..Math.max() -- function returns the largest number fromm the list of arguments
..Basic syntax -- Math.max(value1, value2, ..., valueN)

//code snippet
let numbers = [45, 67, 23, 89, 12];
let minNumber = Math.min(...numbers);
let maxNumber = Math.max(...numbers);
'...' => it is the spread operator 
      => it is used to spread the elements of an array or the characters of a string 
         into seperate arguments or elements
*/

/*
List of more functions : 
..Math.trunc() -- returns the integer part removing fractional part
..Math.sign()  -- returns the sign of the number (1 for positive, -1 for negative, 0 for zero)
..Math.sin(), Math.cos(), Math.tan(): Trigonometric functions for sine, cosine, and tangent.
..Math.asin(), Math.acos(), Math.atan(): Inverse trigonometric functions.
*/

//learning the Math.random() function
console.log(Math.random());
console.log((Math.random()*10) + 1);
console.log(Math.floor(Math.random()*10) + 1);
/*
The Math.random() function returns a floating-point number in the range [0, 1), 
meaning it can return 0 but never 1.
The randomness generated by Math.random() is pseudo-random, which means 
that it's determined by an algorithm and a seed value. 
The generated sequence appears random, but it is entirely deterministic based on 
the seed. 
*/

//formula to obtain a random number within a certain range
const min = 10
const max = 20
console.log(Math.floor((Math.random() * (max - min + 1)) + min));